In [1]:
from __future__ import print_function
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1,3,6,np.nan,4,1]) # similar with 10 numpy
print(s)

0    1.0
1    3.0
2    6.0
3    NaN
4    4.0
5    1.0
dtype: float64


In [5]:
dates = pd.date_range('20160101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])  # columns列,index行
print(df)
print(df['B'])

                   A         B         C         D
2016-01-01 -1.364374  1.785699  1.368524  0.226391
2016-01-02  1.598420 -2.089530  0.958098 -0.803967
2016-01-03  0.272006  0.142945 -1.667050  0.599994
2016-01-04 -1.048698  0.376605 -0.068549  1.656107
2016-01-05 -0.468398 -0.453217 -0.686230 -0.401664
2016-01-06 -0.501126 -0.496239 -2.285627 -0.074838
2016-01-01    1.785699
2016-01-02   -2.089530
2016-01-03    0.142945
2016-01-04    0.376605
2016-01-05   -0.453217
2016-01-06   -0.496239
Freq: D, Name: B, dtype: float64


In [6]:
df2 = pd.DataFrame({'A' : 1,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo'})

In [11]:
print(df2)
print(df2.dtypes)

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  train  foo
A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [12]:
print(df.index)
print(df.columns)

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')


In [13]:
print(df.values)
print(df.describe())

[[-1.36437395  1.78569889  1.36852391  0.22639068]
 [ 1.59842005 -2.0895297   0.95809798 -0.80396689]
 [ 0.27200639  0.14294518 -1.66705007  0.59999437]
 [-1.04869843  0.37660515 -0.06854928  1.65610744]
 [-0.46839808 -0.45321744 -0.68623049 -0.4016642 ]
 [-0.50112565 -0.49623859 -2.28562674 -0.07483814]]
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.252028 -0.122289 -0.396806  0.200337
std    1.065799  1.271145  1.436999  0.863299
min   -1.364374 -2.089530 -2.285627 -0.803967
25%   -0.911805 -0.485483 -1.421845 -0.319958
50%   -0.484762 -0.155136 -0.377390  0.075776
75%    0.086905  0.318190  0.701436  0.506593
max    1.598420  1.785699  1.368524  1.656107


In [16]:
print(df.T)
print(df.sort_index(axis=1, ascending=False))
print(df.sort_values(by='B'))

   2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
A   -1.364374    1.598420    0.272006   -1.048698   -0.468398   -0.501126
B    1.785699   -2.089530    0.142945    0.376605   -0.453217   -0.496239
C    1.368524    0.958098   -1.667050   -0.068549   -0.686230   -2.285627
D    0.226391   -0.803967    0.599994    1.656107   -0.401664   -0.074838
                   D         C         B         A
2016-01-01  0.226391  1.368524  1.785699 -1.364374
2016-01-02 -0.803967  0.958098 -2.089530  1.598420
2016-01-03  0.599994 -1.667050  0.142945  0.272006
2016-01-04  1.656107 -0.068549  0.376605 -1.048698
2016-01-05 -0.401664 -0.686230 -0.453217 -0.468398
2016-01-06 -0.074838 -2.285627 -0.496239 -0.501126
                   A         B         C         D
2016-01-02  1.598420 -2.089530  0.958098 -0.803967
2016-01-06 -0.501126 -0.496239 -2.285627 -0.074838
2016-01-05 -0.468398 -0.453217 -0.686230 -0.401664
2016-01-03  0.272006  0.142945 -1.667050  0.599994
2016-01-04 -1.0486