In [1]:
import numpy as np

In [4]:
a = np.array([2,23,4],dtype=np.int64)
print(a)
print(a.dtype)

[ 2 23  4]
int64


In [6]:
b = np.array([[2,23,4],
             [2,32,4]])
print(b)

[[ 2 23  4]
 [ 2 32  4]]


In [10]:
c = np.zeros([3,4])
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
d = np.ones([3,4])
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
e = np.empty([3,4],dtype=np.float64)
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
f = np.arange(10,20,2)
print(f)

[10 12 14 16 18]


In [19]:
g = np.arange(12).reshape((3,4))
print(g)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
h = np.linspace(1,10,20)
print(h)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [21]:
i = np.linspace(1,10,6).reshape((2,3))
print(i)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
