In [1]:
import numpy as np

In [5]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


In [4]:
c = a-b
print(c)

[10 19 28 37]


In [7]:
d = 10*np.sin(a)
print(d)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [8]:
print(b<3)

[ True  True  True False]


In [20]:
e = np.array([[1,1],
            [0,1]])
b = np.arange(4).reshape((2,2))
print(e,'\n',b)

[[1 1]
 [0 1]] 
 [[0 1]
 [2 3]]


In [30]:
c = e.dot(b)
print(c)
print(e*b)
print(np.multiply(e,b))

[[2 4]
 [2 3]]
[[0 1]
 [0 3]]
[[0 1]
 [0 3]]


In [35]:
f = np.random.random((2,4))
print(f)

[[0.73996787 0.82040368 0.91895022 0.86409579]
 [0.76505106 0.08539311 0.00276214 0.69325549]]


In [38]:
print(np.sum(f))
print(np.sum(f,axis=1)) #axis=1表示行

4.889879359612175
[3.34341756 1.5464618 ]


In [39]:
np.min(f)

0.0027621424151016427

In [40]:
np.max(f)

0.9189502213010543