In [1]:
import numpy as np

In [2]:
A = np.arange(2,14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [3]:
np.argmin(A)

0

In [4]:
np.argmax(A)

11

In [6]:
print(np.mean(A))
print(A.mean())

7.5
7.5


In [7]:
print(np.average(A))

7.5


In [8]:
np.median(A)

7.5

In [9]:
np.cumsum(A) # 累加

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90], dtype=int32)

In [10]:
np.diff(A) # 累差

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
np.nonzero(A)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [15]:
B = np.arange(14,2,-1).reshape((3,4))
print(B)
np.sort(B)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [20]:
print(np.transpose(B))
print(B.T)
print((B.T).dot(B))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [24]:
print(B)
print(np.clip(B,5,9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
