In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [10]:
B = np.arange(3,15).reshape((3,4))
print(B)
print(B[2])
print(B[1,1])
print(B[2,:])
print(B[:,1])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
[11 12 13 14]
[ 4  8 12]


In [11]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [16]:
print(B)
for column in B.T:
    print(column)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [21]:
print(B.flatten())
for item in B.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
