In [1]:
import numpy as np

In [2]:
A = np.array([1,1,1])
B = np.array([2,2,2])

In [3]:
C = np.vstack((A,B)) # vertical stack
print(C)

[[1 1 1]
 [2 2 2]]


In [4]:
D = np.hstack((A,B)) # horizontal stack
print(D)

[1 1 1 2 2 2]


In [12]:
print(A[np.newaxis,:])
print(A[:,np.newaxis])

[[1 1 1]]
[[1]
 [1]
 [1]]


In [13]:
E = np.hstack((A[:,np.newaxis],B[:,np.newaxis]))
print(E)

[[1 2]
 [1 2]
 [1 2]]


In [20]:
F = np.concatenate((A[:,np.newaxis],B[:,np.newaxis],B[:,np.newaxis],A[:,np.newaxis]),axis=0)
print(F)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [21]:
F = np.concatenate((A[:,np.newaxis],B[:,np.newaxis],B[:,np.newaxis],A[:,np.newaxis]),axis=1)
print(F)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
