In [6]:
import numpy as np

In [7]:
a = np.arange(4)

In [8]:
b = a
c = a
d = b
print(b)
print(c)
print(d)

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]


In [9]:
a[0] = 11
print(a)

[11  1  2  3]


In [10]:
print(b)
print(c)
print(d)

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]


In [11]:
d[1:3] = [22,33]

In [13]:
print(a,b,c)

[11 22 33  3] [11 22 33  3] [11 22 33  3]


In [15]:
b = a.copy() # deep copy

In [16]:
a[3] = 100

In [23]:
b

array([11, 22, 33,  3])